version: "3"
services:
  strapi:
    image: observatorio/api-website
    build: .
    command: npm run develop
    ports:
      - "1337:1337"
    volumes:
      - ./api:/app/api/
      - ./config:/app/config/
      - ./extensions:/app/extensions/
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./favicon.ico:/app/favicon.ico
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_NAME=observatorio-website
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=elpatriarcado
      - DATABASE_PASSWORD=sevaacaer
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./.db:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=observatorio-website
      - POSTGRES_USER=elpatriarcado
      - POSTGRES_PASSWORD=sevaacaer
